Update torg mail ru feed
dointeractive/spree_yandex_market pull request #4
Opened 2016-11-18 17:33 UTC by Andreaz01

2016-11-21 12:12 UTC, oleglitvin requested changes

2016-11-21 12:12 UTC, oleglitvin commented on lib/export/torg_mail_ru_exporter.rb
> +              Spree::Taxon.published.where(export_to_yandex_market: true).drop(1).each do |taxon|
If `drop(1)` is intended for skipping the `root` taxon, than I suggest to use a more explicit solution, something like this: 
```ruby
Spree::Taxon.published.where(export_to_yandex_market: true).except(Spree::Taxon.root)
# or
Spree::Taxon.published.where(export_to_yandex_market: true) - [Spree::Taxon.root]
```

2016-11-21 14:05 UTC, Andreaz01 commented
@oleglitvin, done.

2016-11-28 11:54 UTC, dmitrybobylev commented
I'm really tired of all these feeds.
I guess we should implement more beautiful solution.

LGTM

2016-11-28 11:54 UTC, merged